# Sntpd config
listen_addr: ":12303"
worker: 0
minpoll: 4
maxpoll: 10
geodb: GeoLite2-Country.mmdb

stratum_pool:
  - wwv.nist.gov
  - time.nist.gov
  - time-b.nist.gov
  - time-a.nist.gov

stats:
    pro_addr: :7370

restrict:
  - cn 3000/s kod
  - us 100/s  drop
  - default 2000/s kod
